#include "noa/gpu/cuda/Ewise.hpp"
#include "noa/gpu/cuda/utils/EwiseTrinary.cuh"

NOA_CUDA_EWISE_TRINARY_GENERATE_API

#define NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(T)                         \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::plus_t)           \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::plus_minus_t)     \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::plus_multiply_t)  \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::plus_divide_t)    \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::minus_t)          \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::minus_plus_t)     \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::minus_multiply_t) \
    NOA_CUDA_EWISE_TRINARY_INSTANTIATE_API(T,T,T,T,::noa::minus_divide_t)

NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(f16)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(f32)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(f64)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(i8)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(i16)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(i32)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(i64)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(u8)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(u16)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(u32)
NOA_INSTANTIATE_EWISE_TRINARY_ARITHMETIC(u64)
