#include "noa/gpu/cuda/Ewise.hpp"
#include "noa/gpu/cuda/utils/EwiseBinary.cuh"

NOA_CUDA_EWISE_BINARY_GENERATE_API

#define NOA_INSTANTIATE_EWISE_BINARY_SCALAR(T)                          \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::equal_t)         \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::not_equal_t)     \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::less_t)          \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::less_equal_t)    \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::greater_t)       \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::greater_equal_t)

NOA_INSTANTIATE_EWISE_BINARY_SCALAR(i8)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(i16)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(i32)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(i64)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(u8)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(u16)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(u32)
NOA_INSTANTIATE_EWISE_BINARY_SCALAR(u64)

#define NOA_INSTANTIATE_EWISE_BINARY_FLOAT(T)                           \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::equal_t)         \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::not_equal_t)     \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::less_t)          \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::less_equal_t)    \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::greater_t)       \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,T,::noa::greater_equal_t)

NOA_INSTANTIATE_EWISE_BINARY_FLOAT(f16)
NOA_INSTANTIATE_EWISE_BINARY_FLOAT(f32)
NOA_INSTANTIATE_EWISE_BINARY_FLOAT(f64)

#define NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(T, V)              \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::equal_t)         \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::not_equal_t)     \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::less_t)          \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::less_equal_t)    \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::greater_t)       \
    NOA_CUDA_EWISE_BINARY_INSTANTIATE_API(T,T,V,::noa::greater_equal_t)

NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(f16, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(f32, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(f64, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(i8, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(i16, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(i32, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(i64, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(u8, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(u16, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(u32, bool)
NOA_INSTANTIATE_EWISE_BINARY_COMPARISON_CAST(u64, bool)
