function(noa_enable_doxygen)
    option(NOA_ENABLE_DOXYGEN "noa - Enable doxygen doc builds of source" OFF)
    if(NOA_ENABLE_DOXYGEN)
        set(DOXYGEN_CALLER_GRAPH YES)
        set(DOXYGEN_CALL_GRAPH YES)
        set(DOXYGEN_EXTRACT_ALL YES)
        find_package(Doxygen REQUIRED dot)
        doxygen_add_docs(noa-doxygen-docs ${PROJECT_SOURCE_DIR})

    endif()
endfunction()
